name: Testing Suite

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  run-pytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bring up docker images
      run: docker-compose up -d
    - name: Run test suite
      run: docker-compose run snowshu pytest
  run-prospector:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bring up docker images
      run: docker-compose up -d
    - name: Run test suite
      run: docker-compose run snowshu prospector